# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = ["macos/**", "windows/**", "linux/**", "android/**", "ios/**"]
SPDX-FileCopyrightText = "2025 You <your-email@ddress.org>"
SPDX-License-Identifier = "MIT"
